### ISSUE TITLE
Doubles neo fields instead of replacing them

### ISSUE THREAD

**Issue by hellomaud** [digitalpulsebe/craft-multi-translator#21] opened 2024-08-20 14:40 UTC
Hi,

When I try to translate my entries with neo fields it doesn't replace the fields, but it doubles them. With the result that I have the field is in the original language and the translated language. 

It could be something wrong in my settings, I do get this warning: _revision changes will apply on top of the translated Entry_, but how do I prevent this?

I don't seem to have this issue on my single page, but I do have it on my structured page.

**Comment by JodebaDigitalPulse** [comment] 2024-08-21 06:12
Hi, 

I would like some more information to try to reproduce this issue.

- What Craft CMS and Neo version are you working with?
- What is the propagation method the section?
- What is the propagation method of the neo field?

The warning "revision changes will apply on top of the translated Entry" is always there, just as a reminder.

**Comment by hellomaud** [comment] 2024-08-22 07:16
Hi,

- Craft CMS 4.11.3

- Propagation method Section: Let each entry choose which sites it should be saved to

- Propagation method Neo: Only save blocks to the site they were created in

**Comment by JodebaDigitalPulse** [comment] 2024-08-30 14:33
Hi @hellomaud 

I really can't reproduce this problem.
There are some bug fixes in the changelog of Neo, can you try updating neo once more?

If you create this file: config/multi-translator.php with contents:
```<?php

return [
    "debug" => true,
];
```

You will have some logged entries in storage/logs for each translation. Maybe have a look there, or send the logs?

**Comment by JodebaDigitalPulse** [comment] 2024-09-27 08:27
Hi @hellomaud , do you still have this issue? Or can we close this?

**Comment by hellomaud** [comment] 2024-09-30 07:10
I updated neo and have added
```
return [
    "debug" => true,
];
```
to the multi-translator.php so i do have some logs, but i don't know if there's anything linking to the issue i have.

**Comment by dande-sun** [comment] 2024-11-29 07:26
Hi @JodebaDigitalPulse, the multi translator is not working with the neo field, I output the log and found the translation text, but it not update to the neo field, 
"craftcms/cms": "4.13.3",
"spicyweb/craft-neo": "4.2.21",
"digitalpulsebe/craft-multi-translator": "1.14.0",

**Comment by JodebaDigitalPulse** [comment] 2024-12-06 08:40
Hi @dande-sun , from what you described in your email and [the issue you're having with other plugins](https://github.com/Goldinteractive/craft-sitecopy/issues/21), I'm thinking your current neo structure might be corrupted. You could try some [neo console commands](https://github.com/spicywebau/craft-neo/blob/5.x/docs/console-commands.md) to fix your database.

**Closed by JodebaDigitalPulse** 2024-12-06 08:40 UTC

**Comment by dande-sun** [comment] 2024-12-11 09:07
Hi Jonathan De Baere,  I am very certain that this issue is not caused by the "neo structure is corrupted." Even for a newly created db, section, or fields, as long as it is a neo field, it will not translate.




________________________________

**Comment by dande-sun** [comment] 2024-12-11 09:55
Attached are the database backup and composer.json.

________________________________

**Comment by JodebaDigitalPulse** [comment] 2024-12-13 08:48
Hi @dande-sun, your attachments are not included on github. The database and composer would not be enough to determine the problem. 

You also need to make sure all the fields are translatable, like this:
![image](https://github.com/user-attachments/assets/716911a8-ce0d-4f59-a389-a9f88ae32ace)
And the propagation method of the entries and the neo field is allowing for translations for each site:
![image](https://github.com/user-attachments/assets/043e34ad-6889-4245-bc8f-a1c26628a126)

I also tested with a clean setup, you can try this demo where it is working: please try this project 
[craft.zip](https://github.com/user-attachments/files/18123659/craft.zip)
Run ddev, composer and follow the craft install wizard to get it running.
